baseurl = "http://www.ultrashuffle.co.uk/"
languageCode = "en-us"
title = "Ultrashuffle - A slow motion adventure up hills and through bogs!"
disqusShortname = "ultrashuffle"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 20

[taxonomies]
    tag = "tags"

[author]
    name = "Tom Elliff"

[params]
    home = "Ultrashuffle"
    tagline = "A slow motion adventure up hills and through bogs"
    gravatarHash = "cb6c6c20f2613c8af1967a5dcd79152e"
    customCSS = "css/mind-over-matter.css"
    rss = true
    truncate = true
